spring:
  application:
    name: rpt-config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/NatsuSai/config-repo-demo

server:
  port: 8762

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/