spring:
  application:
    name: trace-1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8083

logging:
  level:
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: debug