spring:
  application:
    name: rpt-eureka-server

server:
  port: 8761

eureka:
  client:
#    register-with-eureka: false
#    fetch-registry: false
    serviceUrl:
          defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: false
  dashboard:
    path: /
  instance:
    hostname: localhost