spring:
  application:
    name: rpt-turbine
server:
  port: 9010
management:
  port: 9011
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
turbine:
  app-config: rpt-gateway
  combine-host-port: true
